name: Build, Push, and Update GitOps

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
env:

  IMAGE_NAME: auth-service
  GCP_PROJECT_ID: personal-473312
  GCP_ARTIFACT_LOCATION: us-central1
  GCP_REPO_NAME: microservice



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source repo
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build 
        run: |
          IMAGE="${{ env.GCP_ARTIFACT_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.IMAGE_NAME }}"
          TAG=${{ github.run_number }}
          docker build -t $IMAGE:$TAG .
          docker images
# docker push $IMAGE:$TAG
# echo "NEW_TAG=$TAG" >> $GITHUB_ENV
# echo "IMAGE=$IMAGE" >> $GITHUB_ENV

